kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-pv
  namespace: kube-system
  labels:
    type: local
spec:
  storageClassName: prometheus
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/prometheusdata"
